CREATE DATABASE TAQUILLASBD;

USE TAQUILLABD;

CREATE TABLE DEPARTAMENTO(
idDepartamento INT NOT NULL,
nombre VARCHAR(45) NOT NULL
);
ALTER TABLE DEPARTAMENTO ADD PRIMARY KEY (idDepartamento);

CREATE TABLE MUNICIPIO(
idMunicipio INT NOT NULL,
nombre VARCHAR(45) NOT NULL,
idDepartamento INT NOT NULL
);
ALTER TABLE MUNICIPIO ADD PRIMARY KEY (idMunicipio);
ALTER TABLE MUNICIPIO ADD CONSTRAINT fk_iddepa FOREIGN KEY (idDepartamento) REFERENCES DEPARTAMENTO (idDepartamento);

CREATE TABLE CINE(
idCine INT NOT NULL,
nombre VARCHAR(45),
idMunicipio INT,
direccion VARCHAR(45)
);
ALTER TABLE CINE ADD PRIMARY KEY (idCine);
ALTER TABLE CINE ADD CONSTRAINT fk_idmunic FOREIGN KEY (idMunicipio) REFERENCES MUNICIPIO (idMunicipio);

CREATE TABLE TAMANOSALA(
idTipoSala INT NOT NULL,
nombre VARCHAR(45),
noAsientos INT
);
ALTER TABLE TAMANOSALA ADD PRIMARY KEY(idTipoSala);


CREATE TABLE SALA(
idSala INT NOT NULL,
numero INT NOT NULL,
idTipoSala INT NOT NULL,
idCine INT NOT NULL,
estatus TINYINT
);
ALTER TABLE SALA ADD PRIMARY KEY (idSala,idCine);
ALTER TABLE SALA ADD CONSTRAINT fk_salacine FOREIGN KEY (idCine) REFERENCES CINE (idCine);
ALTER TABLE SALA ADD CONSTRAINT fk_salatiposala FOREIGN KEY (idTipoSala) REFERENCES TAMANOSALA (idTipoSala);

CREATE TABLE FORMATO (
idFormato INT,
nombre VARCHAR(45)
);
ALTER TABLE FORMATO ADD PRIMARY KEY(idFormato);

CREATE TABLE FORMATOSALA(
idSala INT NOT NULL,
idFormato INT NOT NULL
);
ALTER TABLE FORMATOSALA ADD PRIMARY KEY(idSala,idFormato);
ALTER TABLE FORMATOSALA ADD CONSTRAINT fk_fmsidsala FOREIGN KEY (idSala) REFERENCES SALA (idSala);
ALTER TABLE FORMATOSALA ADD CONSTRAINT fk_fmsidformato FOREIGN KEY (idFormato) REFERENCES FORMATO (idFormato);

CREATE TABLE IDIOMA(
idIdioma INT NOT NULL,
nombre VARCHAR(45)
);
ALTER TABLE IDIOMA ADD PRIMARY KEY(idIdioma);

CREATE TABLE CLASIFICACIONPELICULA(
idClasificacionPelicula INT NOT NULL,
nombre VARCHAR(45),
descripcion VARCHAR(355)
);
ALTER TABLE CLASIFICACIONPELICULA ADD PRIMARY KEY(idClasificacionPelicula);

CREATE TABLE PELICULA(
idPelicula INT NOT NULL,
nombre VARCHAR(45),
descripcion VARCHAR(245),
idClasificacion INT,
fechaestreno DATETIME,
estatus TINYINT,
linkTrailer VARCHAR(45),
imagen VARCHAR(45),
duracion VARCHAR(15)
);
ALTER TABLE PELICULA ADD PRIMARY KEY (idPelicula);
ALTER TABLE PELICULA ADD CONSTRAINT fk_peliclas FOREIGN KEY (idClasificacion) REFERENCES CLASIFICACIONPELICULA (idClasificacionPelicula);

CREATE TABLE PROYECCIONPELICULA(
idProyeccionPelicula INT NOT NULL,
idPelicula INT,
idSala INT,
idIdioma INT,
idFormato INT,
fechaHoraProyeccion DATETIME
);
ALTER TABLE PROYECCIONPELICULA ADD PRIMARY KEY(idProyeccionPelicula);
ALTER TABLE PROYECCIONPELICULA ADD CONSTRAINT fk_ppidioma FOREIGN KEY (idIdioma) REFERENCES IDIOMA (idIdioma);
ALTER TABLE PROYECCIONPELICULA ADD CONSTRAINT fk_pppelicua FOREIGN KEY (idPelicula) REFERENCES PELICULA (idPelicula);
ALTER TABLE PROYECCIONPELICULA ADD CONSTRAINT fk_ppformato FOREIGN KEY (idSala) REFERENCES SALA (idSala);
ALTER TABLE PROYECCIONPELICULA ADD CONSTRAINT fk_ppsala FOREIGN KEY (idFormato) REFERENCES FORMATO (idFormato);

CREATE TABLE CLIENTE(
idCliente INT NOT NULL,
numeroTarjeta INT,
puntos DOUBLE,
nombreClienteTarjeta VARCHAR(35),
apellidoClienteTarjeta VARCHAR(35)
);
ALTER TABLE CLIENTE ADD PRIMARY KEY(idCliente);

CREATE TABLE RESERVACIONENCABEZADO(
idReservacionEncabezado INT NOT NULL,
fecha DATETIME,
nombre VARCHAR(25),
apellido VARCHAR(25),
nit INT, 
correo VARCHAR(45),
total DOUBLE,
descuento DOUBLE,
idProyeccionPelicula INT,
estadoPago TINYINT,
numeroFactura INT,
idCliente INT
);
ALTER TABLE RESERVACIONENCABEZADO ADD PRIMARY KEY(idReservacionEncabezado);
ALTER TABLE RESERVACIONENCABEZADO ADD CONSTRAINT fk_reproyeccion FOREIGN KEY (idProyeccionPelicula) REFERENCES PROYECCIONPELICULA (idProyeccionPelicula);
ALTER TABLE RESERVACIONENCABEZADO ADD CONSTRAINT fk_rrcliente FOREIGN KEY (idCliente) REFERENCES CLIENTE (idCliente);

CREATE TABLE TIPOBOLETO(
idTipoBoleto INT NOT NULL,
nombre VARCHAR(45)
);
ALTER TABLE TIPOBOLETO ADD PRIMARY KEY(idTipoBoleto);


CREATE TABLE BOLETO(
idBoleto INT NOT NULL,
idTipoBoleto INT,
precio DOUBLE,
idFormato INT
);
ALTER TABLE BOLETO ADD PRIMARY KEY(idBoleto,idFormato);
ALTER TABLE BOLETO ADD CONSTRAINT fk_boletoformato FOREIGN KEY (idFormato) REFERENCES FORMATO (idFormato);
ALTER TABLE BOLETO ADD CONSTRAINT fk_boletotipoboleto FOREIGN KEY (idTipoBoleto) REFERENCES TIPOBOLETO (idTipoBoleto);

CREATE TABLE PROMOCION(
idPromocion INT NOT NULL,
NombrePromocion VARCHAR(45),
CantidadDescuento DOUBLE,
fechaInicio DATETIME,
fechaFinal DATETIME,
idBoleto INT
);
ALTER TABLE PROMOCION ADD PRIMARY KEY(idPromocion);
ALTER TABLE PROMOCION ADD CONSTRAINT fk_promoboleto FOREIGN KEY (idBoleto) REFERENCES BOLETO (idBoleto);

CREATE TABLE RESERVACIONDETALLE(
idReservacionDetalle INT NOT NULL,
idBoleto INT,
idReservacionEncabezado INT,
cantidad INT,
idPromocion INT
);
ALTER TABLE RESERVACIONDETALLE ADD PRIMARY KEY(idReservacionDetalle);
ALTER TABLE RESERVACIONDETALLE ADD CONSTRAINT fk_resdetboleto FOREIGN KEY (idBoleto) REFERENCES BOLETO (idBoleto);
ALTER TABLE RESERVACIONDETALLE ADD CONSTRAINT fk_resdetresenca FOREIGN KEY (idReservacionEncabezado) REFERENCES RESERVACIONENCABEZADO (idReservacionEncabezado);
ALTER TABLE RESERVACIONDETALLE ADD CONSTRAINT fk_resdetpromocion FOREIGN KEY (idPromocion) REFERENCES PROMOCION (idPromocion);


CREATE TABLE ASIENTO(
fila INT NOT NULL,
numero INT NOT NULL,
idReservacionDetalle INT NOT NULL
);
ALTER TABLE ASIENTO ADD PRIMARY KEY (fila,numero,idReservacionDetalle);
ALTER TABLE ASIENTO ADD CONSTRAINT fk_asientoreservaciondetalle FOREIGN KEY (idReservacionDetalle) REFERENCES RESERVACIONDETALLE (idReservacionDetalle);

CREATE TABLE ROL(
idRol INT NOT NULL,
nombre VARCHAR(45)
);
ALTER TABLE ROL ADD PRIMARY KEY(idRol);

CREATE TABLE PUESTO(
idPuesto INT NOT NULL,
sueldo DOUBLE,
nombre VARCHAR(45)
);
ALTER TABLE PUESTO ADD PRIMARY KEY(idPuesto);

CREATE TABLE EMPLEADO(
idEmpleado INT NOT NULL,
nombre VARCHAR(45),
apellido VARCHAR(45),
idPuesto INT,
fechaContratacion DATETIME,
fechaNacimiento DATETIME
);
ALTER TABLE EMPLEADO ADD PRIMARY KEY(idEmpleado);
ALTER TABLE EMPLEADO ADD CONSTRAINT fk_emppuesto FOREIGN KEY (idPuesto) REFERENCES PUESTO (idPuesto);


CREATE TABLE CORREO(
idCorreo INT NOT NULL,
correo VARCHAR(45),
idEmpleado INT
);
ALTER TABLE CORREO ADD PRIMARY KEY(idCorreo);
ALTER TABLE CORREO ADD CONSTRAINT fk_correoemp FOREIGN KEY (idEmpleado) REFERENCES EMPLEADO (idEmpleado);

CREATE TABLE TELEFONO(
idTelefono INT NOT NULL,
telefono VARCHAR(45),
idEmpleado INT
);
ALTER TABLE TELEFONO ADD PRIMARY KEY(idTelefono);
ALTER TABLE TELEFONO ADD CONSTRAINT fk_telefonoemp FOREIGN KEY (idEmpleado) REFERENCES EMPLEADO (idEmpleado);

CREATE TABLE USUARIO(
idUsuario INT NOT NULL,
idEmpleado INT,
idRol INT,
contrasenia VARCHAR(30),
nombreUsuario VARCHAR(45)
);
ALTER TABLE USUARIO ADD PRIMARY KEY(idUsuario);
ALTER TABLE USUARIO ADD CONSTRAINT fk_userempleado FOREIGN KEY (idEmpleado) REFERENCES EMPLEADO (idEmpleado);
ALTER TABLE USUARIO ADD CONSTRAINT fk_userrol FOREIGN KEY (idRol) REFERENCES ROL (idRol);


CREATE TABLE BITACORA(
idBitacora INT NOT NULL,
fecha DATETIME,
idUsuario INT,
ipAddress VARCHAR(45),
proceso VARCHAR(45),
tabla VARCHAR(45)
);
ALTER TABLE BITACORA ADD PRIMARY KEY(idBitacora);
ALTER TABLE BITACORA ADD CONSTRAINT fk_bitacorauser FOREIGN KEY (idUsuario) REFERENCES USUARIO (idUsuario);






